### ISSUE TITLE
Update GUI menu loop

### ISSUE THREAD

**Issue by iSupersniper** [PermaNulled/cartographer#103]
When there are no updates, the text just displays empty strings after the download and install text.

Also if you select B to cancel on the menu instead of the actual button that says cancel. the menu will close and reopen.

**Comment by KILLER-CHIEF** [comment]
The reopening behaviour is on purpose due to a bug with the menu's closing when clicking anywhere that isn't a button. It is to prevent accidental closure. The B button doesn't work because it hasn't been directly reversed and is tied to that closing behaviour.

When there are no updates the text should be changed to instead say that.

**Comment by pnill** [comment]
Can we close this? is it still relevant?

**Comment by KILLER-CHIEF** [comment]
Fixed text as requested: https://github.com/PermaNulled/cartographer/commit/1a1c272f5e775fcd27e7d3f44b025fc00e9bb58e
Closed.
