### ISSUE TITLE
Multiple clients same machine issue

### ISSUE THREAD

**Issue by shayaantx** [PermaNulled/cartographer#108]
Basically when I'm hosting 2 clients from same machine and some random joins, the 3rd player basically does not register properly.

To the 3rd player, they aren't even in the game. To the host, they are partially in the game (I can see them, but their name data is missing)

Not many people use this feature so its not a big deal, but, noting it for future if anyone wants to attempt to fix.

**Comment by pnill** [comment]
Were you using the WANIP/LANIP option when doing this vs the NAT Loopback from your router? I suspect this occurs when those options are used because the host is responsible for transferring the data about additional players... and due to the host understanding that the data for the player is an internal IP it gives the other player said internal IP. 

Why it impacts them in this way I'm not sure, it's something I've wanted to research for sure though... we'll need to do some in-depth logging surrounding secure addresses and such.

Actually come to think about it, the second client wouldn't have opened a port on the NAT of the router so the data wouldn't be able to reach back to them even if the address was your WAN address I'll have to look into some way to resolve this.

It references: https://github.com/PermaNulled/cartographer/issues/97

**Comment by pnill** [comment]
Tracking in #97 instead.
