### ISSUE TITLE
Localization for Project Cartographer

### ISSUE THREAD

**Issue by CarlosACepeda** [PermaNulled/cartographer#247]
Hi devs!
I was checking out the source and I see, for example that the custom Carto's menus contains hard coded text in english, so I was wondering, would be possible to localize those texts so they use the same language the game is on?

For example here: [Custom Menu](https://github.com/PermaNulled/cartographer/blob/development/xlive/H2MOD/Modules/CustomMenu/CustomMenu.cpp#L4849)

**Comment by bigtweekx** [comment]
https://github.com/PermaNulled/cartographer/blob/development/xlive/H2MOD/Modules/CustomMenu/CustomMenu.cpp#L4923

**Comment by CarlosACepeda** [comment]
Oh no, maybe I'm not making myself understand.
If I set the game language to other than english, Cartographer's menus keeps in english.

**Comment by pnill** [comment]
Unless someone makes a pull request introducing multi-lingual support for cartographer menus I don't see it happening.

**Comment by KILLER-CHIEF** [comment]
There is a file called h2customlanguage.ini in the root of the game's install directory that is downloaded when you do an update and created when you go to the custom language part of the cartographer menu in-game and hit "Capture New Labels" then stop capture and save. Basically while in capture mode, any strings you see on screen will be recorded and when you stop and save the file you will see those new labels there and modify them and reload the file into the game. Remember if you installed the game with admin permission, you will need to run the game in admin permission in order to write the new language file out.
