### ISSUE TITLE
[0.5.4.0] Unconfirmed reports of players getting kicked out of servers 2 minutes after joining

### ISSUE THREAD

**Issue by bigtweekx** [PermaNulled/cartographer#256]
Unknown if this is related to project code or server tools messing up. Just making a note of this for future reference

**Comment by Himanshu-01** [comment]
## Steps to reproduce :
#1
* Join a custom map lobby
* When Confirm Download popup occurs , choose Leave Game/Cancle
* Quickly Join other server
* You get booted after 20 seconds since the popup

#2
* Join a Custom Maps lobby
* If the confirm download popup comes , and the host / server changes the map and the  popup 
   disappears without you choosing "Download Map"
* You get booted after 20 seconds
