### ISSUE TITLE
Client - Server List Refresh

### ISSUE THREAD

**Issue by AnotherRandomTech** [PermaNulled/cartographer#45]
Issues: 
Issues with Network server list with so many Dedicated servers running at once. Makes it difficult to select the right game you want to join. 

Believe a combination of Server Network list refresh times and connection lag time.

**Comment by KILLER-CHIEF** [comment]
The client essentially needs to be modded to accept packets from the master relay older than ~1.5 seconds. This is most likely due to connection time between you (a client) to the master relay.
I have looked into this myself but never found the ~1.5 seconds in the code anywhere. I've yet to have another attempt.

**Comment by KILLER-CHIEF** [comment]
`halo2.exe+51c45c`
probably when used in `halo2.exe+1b4f46`
is a bool that stops the server list from refreshing. However it also prevents you from joining games while 0 (switch to 1 as you join for it to work).
This or the logic behind it can be altered to fix this problem.

**Comment by pnill** [comment]
We'll be replacing server list with CEF eventually, this is a wontfix.

**Comment by KILLER-CHIEF** [comment]
I just fixed this popping in and out game servers issue on the server list for users with poor internet connection to the master relay. Essentially I just set the LAN Server List 'Ping Frequency' & 'Delete Entry After' timeouts to a higher value in the client. The default was 1500 & 2000 and is now set to 3000 & 9000 respectively. This fix will appear in the next update.
